[lutris]
migration_version = 8
dont-support-lutris = True
show_advanced_options = False
runners_manager_width = 1878
runners_manager_height = 960
width = 1051
height = 600
maximized = False
dark_theme = True
right_side_panel_visible = False
icon_type_gridview = banner
filter_installed = True
view_type = grid
left_side_panel_visible = True
view_sorting = name
view_sorting_ascending = True
dismiss-missing-vulkan-library-warning = True

[list view]
name_column_width = 200
year_column_width = 60
runner_column_width = 120
platform_column_width = 120
lastplayed_column_width = 120
installedat_column_width = 120
playtime_column_width = 100

