'use strict';

var COUNTRIES = [{
  name: 'Afghanistan',
  code: 'af',
  locale: 'fa_AF'
}, {
  name: 'Albania',
  code: 'al',
  locale: 'sq_AL'
}, {
  name: 'Algeria',
  code: 'dz',
  locale: 'ar_DZ'
}, {
  name: 'American Samoa',
  code: 'as',
  locale: 'en_AS'
}, {
  name: 'Andorra',
  code: 'ad',
  locale: 'ca_AD'
}, {
  name: 'Angola',
  code: 'ao',
  locale: 'pt_AO'
}, {
  name: 'Anguilla',
  code: 'ai',
  locale: 'en_AI'
}, {
  name: 'Antigua and Barbuda',
  code: 'ag',
  locale: 'en_AG'
}, {
  name: 'Argentina',
  code: 'ar',
  locale: 'es_AR'
}, {
  name: 'Armenia',
  code: 'am',
  locale: 'hy_AM'
}, {
  name: 'Aruba',
  code: 'aw',
  locale: 'nl_AW'
}, {
  name: 'Australia',
  code: 'au',
  locale: 'en_AU'
}, {
  name: 'Austria',
  code: 'at',
  locale: 'de_AT'
}, {
  name: 'Azerbaijan',
  code: 'az',
  locale: 'az_AZ'
}, {
  name: 'Bahamas',
  code: 'bs',
  locale: 'en_BS'
}, {
  name: 'Bahrain',
  code: 'bh',
  locale: 'ar_BH'
}, {
  name: 'Bangladesh',
  code: 'bd',
  locale: 'bn_BD'
}, {
  name: 'Barbados',
  code: 'bb',
  locale: 'en_BB'
}, {
  name: 'Belarus',
  code: 'by',
  locale: 'be_BY'
}, {
  name: 'Belgium',
  code: 'be',
  locale: 'nl_BE'
}, {
  name: 'Belize',
  code: 'bz',
  locale: 'en_BZ'
}, {
  name: 'Benin',
  code: 'bj',
  locale: 'fr_BJ'
}, {
  name: 'Bermuda',
  code: 'bm',
  locale: 'en_BM'
}, {
  name: 'Bhutan',
  code: 'bt',
  locale: 'dz_BT'
}, {
  name: 'Bolivia',
  code: 'bo',
  locale: 'es_BO'
}, {
  name: 'Bonaire',
  code: 'bq',
  locale: 'NL-BQ1'
}, {
  name: 'Bosnia and Herzegovina',
  code: 'ba',
  locale: 'bs_BA'
}, {
  name: 'Botswana',
  code: 'bw',
  locale: 'en_BW'
}, {
  name: 'Brazil',
  code: 'br',
  locale: 'pt_BR'
}, {
  name: 'British Indian Ocean Territory',
  code: 'io',
  locale: 'en_IO'
}, {
  name: 'British Virgin Islands',
  code: 'vg',
  locale: 'en_VG'
}, {
  name: 'Brunei',
  code: 'bn',
  locale: 'ms_BN'
}, {
  name: 'Bulgaria',
  code: 'bg',
  locale: 'bg_BG'
}, {
  name: 'Burkina Faso',
  code: 'bf',
  locale: 'fr_BF'
}, {
  name: 'Burundi',
  code: 'bi',
  locale: 'fr_BI'
}, {
  name: 'Cabo Verde',
  code: 'cv',
  locale: 'pt_CV'
}, {
  name: 'Cambodia',
  code: 'kh',
  locale: 'km_KH'
}, {
  name: 'Cameroon',
  code: 'cm',
  locale: 'en_CM'
}, {
  name: 'Canada',
  code: 'ca',
  locale: 'en_CA'
}, {
  name: 'Cayman Islands',
  code: 'ky',
  locale: 'en_KY'
}, {
  name: 'Central African Republic',
  code: 'cf',
  locale: 'fr_CF'
}, {
  name: 'Chad',
  code: 'td',
  locale: 'fr_TD'
}, {
  name: 'Chile',
  code: 'cl',
  locale: 'es_CL'
}, {
  name: 'China',
  code: 'cn',
  locale: 'zh_CN'
}, {
  name: 'Christmas Island',
  code: 'cx',
  locale: 'en_CX'
}, {
  name: 'Cocos [Keeling] Islands',
  code: 'cc',
  locale: 'ms_CC'
}, {
  name: 'Colombia',
  code: 'co',
  locale: 'es_CO'
}, {
  name: 'Comoros',
  code: 'km',
  locale: 'ar_KM'
}, {
  name: 'Cook Islands',
  code: 'ck',
  locale: 'en_CK'
}, {
  name: 'Costa Rica',
  code: 'cr',
  locale: 'es_CR'
}, {
  name: 'Croatia',
  code: 'hr',
  locale: 'hr_HR'
}, {
  name: 'Cuba',
  code: 'cu',
  locale: 'es_CU'
}, {
  name: 'Curacao',
  code: 'cw',
  locale: 'nl_CW'
}, {
  name: 'Cyprus',
  code: 'cy',
  locale: 'el_CY'
}, {
  name: 'Czech Republic',
  code: 'cz',
  locale: 'cs_CZ'
}, {
  name: 'Democratic Republic of the Congo',
  code: 'cd',
  locale: 'fr_CD'
}, {
  name: 'Denmark',
  code: 'dk',
  locale: 'da_DK'
}, {
  name: 'Djibouti',
  code: 'dj',
  locale: 'fr_DJ'
}, {
  name: 'Dominica',
  code: 'dm',
  locale: 'en_DM'
}, {
  name: 'Dominican Republic',
  code: 'do',
  locale: 'es_DO'
}, {
  name: 'Ecuador',
  code: 'ec',
  locale: 'es_EC'
}, {
  name: 'Egypt',
  code: 'eg',
  locale: 'ar_EG'
}, {
  name: 'El Salvador',
  code: 'sv',
  locale: 'es_SV'
}, {
  name: 'Equatorial Guinea',
  code: 'gq',
  locale: 'es_GQ'
}, {
  name: 'Eritrea',
  code: 'er',
  locale: 'aa_ER'
}, {
  name: 'Estonia',
  code: 'ee',
  locale: 'et_EE'
}, {
  name: 'Eswatini',
  code: 'sz',
  locale: 'en_SZ'
}, {
  name: 'Ethiopia',
  code: 'et',
  locale: 'am_ET'
}, {
  name: 'Falkland Islands',
  code: 'fk',
  locale: 'en_FK'
}, {
  name: 'Faroe Islands',
  code: 'fo',
  locale: 'fo_FO'
}, {
  name: 'Fiji',
  code: 'fj',
  locale: 'en_FJ'
}, {
  name: 'Finland',
  code: 'fi',
  locale: 'fi_FI'
}, {
  name: 'France',
  code: 'fr',
  locale: 'fr_FR'
}, {
  name: 'French Guiana',
  code: 'gf',
  locale: 'fr_GF'
}, {
  name: 'French Polynesia',
  code: 'pf',
  locale: 'fr_PF'
}, {
  name: 'French Southern Territories',
  code: 'tf',
  locale: 'fr_TF'
}, {
  name: 'Gabon',
  code: 'ga',
  locale: 'fr_GA'
}, {
  name: 'Gambia',
  code: 'gm',
  locale: 'en_GM'
}, {
  name: 'Georgia',
  code: 'ge',
  locale: 'ka_GE'
}, {
  name: 'Germany',
  code: 'de',
  locale: 'de_DE'
}, {
  name: 'Ghana',
  code: 'gh',
  locale: 'en_GH'
}, {
  name: 'Gibraltar',
  code: 'gi',
  locale: 'en_GI'
}, {
  name: 'Greece',
  code: 'gr',
  locale: 'el_GR'
}, {
  name: 'Greenland',
  code: 'gl',
  locale: 'kl_GL'
}, {
  name: 'Grenada',
  code: 'gd',
  locale: 'en_GD'
}, {
  name: 'Guadeloupe',
  code: 'gp',
  locale: 'fr_GP'
}, {
  name: 'Guam',
  code: 'gu',
  locale: 'en_GU'
}, {
  name: 'Guatemala',
  code: 'gt',
  locale: 'es_GT'
}, {
  name: 'Guernsey',
  code: 'gg',
  locale: 'en_GG'
}, {
  name: 'Guinea',
  code: 'gn',
  locale: 'fr_GN'
}, {
  name: 'Guinea-Bissau',
  code: 'gw',
  locale: 'pt_GW'
}, {
  name: 'Guyana',
  code: 'gy',
  locale: 'en_GY'
}, {
  name: 'Haiti',
  code: 'ht',
  locale: 'ht_HT'
}, {
  name: 'Heard Island and McDonald Islands',
  code: 'hm',
  locale: 'hm_HM'
}, {
  name: 'Honduras',
  code: 'hn',
  locale: 'es_HN'
}, {
  name: 'Hong Kong',
  code: 'hk',
  locale: 'zh_HK'
}, {
  name: 'Hungary',
  code: 'hu',
  locale: 'hu_HU'
}, {
  name: 'Iceland',
  code: 'is',
  locale: 'is_IS'
}, {
  name: 'India',
  code: 'in',
  locale: 'en_IN'
}, {
  name: 'Indonesia',
  code: 'id',
  locale: 'id_ID'
}, {
  name: 'Iran',
  code: 'ir',
  locale: 'fa_IR'
}, {
  name: 'Iraq',
  code: 'iq',
  locale: 'ar_IQ'
}, {
  name: 'Ireland',
  code: 'ie',
  locale: 'en_IE'
}, {
  name: 'Isle of Man',
  code: 'im',
  locale: 'en_IM'
}, {
  name: 'Israel',
  code: 'il',
  locale: 'he_IL'
}, {
  name: 'Italy',
  code: 'it',
  locale: 'it_IT'
}, {
  name: 'Ivory Coast',
  code: 'ci',
  locale: 'fr_CI'
}, {
  name: 'Jamaica',
  code: 'jm',
  locale: 'en_JM'
}, {
  name: 'Japan',
  code: 'jp',
  locale: 'ja_JP'
}, {
  name: 'Jersey',
  code: 'je',
  locale: 'en_JE'
}, {
  name: 'Jordan',
  code: 'jo',
  locale: 'ar_JO'
}, {
  name: 'Kazakhstan',
  code: 'kz',
  locale: 'kk_KZ'
}, {
  name: 'Kenya',
  code: 'ke',
  locale: 'en_KE'
}, {
  name: 'Kiribati',
  code: 'ki',
  locale: 'en_KI'
}, {
  name: 'Kosovo',
  code: 'xk',
  locale: 'sq_XK'
}, {
  name: 'Kuwait',
  code: 'kw',
  locale: 'ar_KW'
}, {
  name: 'Kyrgyzstan',
  code: 'kg',
  locale: 'ky_KG'
}, {
  name: 'Laos',
  code: 'la',
  locale: 'lo_LA'
}, {
  name: 'Latvia',
  code: 'lv',
  locale: 'lv_LV'
}, {
  name: 'Lebanon',
  code: 'lb',
  locale: 'ar_LB'
}, {
  name: 'Lesotho',
  code: 'ls',
  locale: 'en_LS'
}, {
  name: 'Liberia',
  code: 'lr',
  locale: 'en_LR'
}, {
  name: 'Libya',
  code: 'ly',
  locale: 'ar_LY'
}, {
  name: 'Liechtenstein',
  code: 'li',
  locale: 'de_LI'
}, {
  name: 'Lithuania',
  code: 'lt',
  locale: 'lt_LT'
}, {
  name: 'Luxembourg',
  code: 'lu',
  locale: 'lb_LU'
}, {
  name: 'Macao',
  code: 'mo',
  locale: 'zh'
}, {
  name: 'Madagascar',
  code: 'mg',
  locale: 'fr_MG'
}, {
  name: 'Malawi',
  code: 'mw',
  locale: 'ny'
}, {
  name: 'Malaysia',
  code: 'my',
  locale: 'ms_MY'
}, {
  name: 'Maldives',
  code: 'mv',
  locale: 'dv'
}, {
  name: 'Mali',
  code: 'ml',
  locale: 'fr_ML'
}, {
  name: 'Malta',
  code: 'mt',
  locale: 'mt_MT'
}, {
  name: 'Marshall Islands',
  code: 'mh',
  locale: 'mh'
}, {
  name: 'Martinique',
  code: 'mq',
  locale: 'fr_MQ'
}, {
  name: 'Mauritania',
  code: 'mr',
  locale: 'ar_MR'
}, {
  name: 'Mauritius',
  code: 'mu',
  locale: 'en_MU'
}, {
  name: 'Mayotte',
  code: 'yt',
  locale: 'fr_YT'
}, {
  name: 'Mexico',
  code: 'mx',
  locale: 'es_MX'
}, {
  name: 'Micronesia',
  code: 'fm',
  locale: 'en_FM'
}, {
  name: 'Moldova',
  code: 'md',
  locale: 'ro_MD'
}, {
  name: 'Monaco',
  code: 'mc',
  locale: 'fr_MC'
}, {
  name: 'Mongolia',
  code: 'mn',
  locale: 'mn_MN'
}, {
  name: 'Montenegro',
  code: 'me',
  locale: 'sr_ME'
}, {
  name: 'Montserrat',
  code: 'ms',
  locale: 'en_MS'
}, {
  name: 'Morocco',
  code: 'ma',
  locale: 'ar_MA'
}, {
  name: 'Mozambique',
  code: 'mz',
  locale: 'pt_MZ'
}, {
  name: 'Myanmar [Burma]',
  code: 'mm',
  locale: 'my'
}, {
  name: 'Namibia',
  code: 'na',
  locale: 'en_NA'
}, {
  name: 'Nauru',
  code: 'nr',
  locale: 'na'
}, {
  name: 'Nepal',
  code: 'np',
  locale: 'ne_NP'
}, {
  name: 'Netherlands',
  code: 'nl',
  locale: 'nl_NL'
}, {
  name: 'New Caledonia',
  code: 'nc',
  locale: 'fr_NC'
}, {
  name: 'New Zealand',
  code: 'nz',
  locale: 'en_NZ'
}, {
  name: 'Nicaragua',
  code: 'ni',
  locale: 'es_NI'
}, {
  name: 'Niger',
  code: 'ne',
  locale: 'fr_NE'
}, {
  name: 'Nigeria',
  code: 'ng',
  locale: 'en_NG'
}, {
  name: 'Niue',
  code: 'nu',
  locale: 'niu'
}, {
  name: 'Norfolk Island',
  code: 'nf',
  locale: 'en_NF'
}, {
  name: 'North Korea',
  code: 'kp',
  locale: 'ko_KP'
}, {
  name: 'North Macedonia',
  code: 'mk',
  locale: 'mk_MK'
}, {
  name: 'Northern Mariana Islands',
  code: 'mp',
  locale: 'fil'
}, {
  name: 'Norway',
  code: 'no',
  locale: 'no_NO'
}, {
  name: 'Oman',
  code: 'om',
  locale: 'ar_OM'
}, {
  name: 'Pakistan',
  code: 'pk',
  locale: 'ur_PK'
}, {
  name: 'Palau',
  code: 'pw',
  locale: 'pau'
}, {
  name: 'Palestine',
  code: 'ps',
  locale: 'ar_PS'
}, {
  name: 'Panama',
  code: 'pa',
  locale: 'es_PA'
}, {
  name: 'Papua New Guinea',
  code: 'pg',
  locale: 'en_PG'
}, {
  name: 'Paraguay',
  code: 'py',
  locale: 'es_PY'
}, {
  name: 'Peru',
  code: 'pe',
  locale: 'es_PE'
}, {
  name: 'Philippines',
  code: 'ph',
  locale: 'tl_PH'
}, {
  name: 'Pitcairn Islands',
  code: 'pn',
  locale: 'en_PN'
}, {
  name: 'Poland',
  code: 'pl',
  locale: 'pl_PL'
}, {
  name: 'Portugal',
  code: 'pt',
  locale: 'pt_PT'
}, {
  name: 'Puerto Rico',
  code: 'pr',
  locale: 'en_PR'
}, {
  name: 'Qatar',
  code: 'qa',
  locale: 'ar_QA'
}, {
  name: 'Republic of the Congo',
  code: 'cg',
  locale: 'fr_CG'
}, {
  name: 'Romania',
  code: 'ro',
  locale: 'ro_RO'
}, {
  name: 'Russia',
  code: 'ru',
  locale: 'ru_RU'
}, {
  name: 'Rwanda',
  code: 'rw',
  locale: 'rw_RW'
}, {
  name: 'Réunion',
  code: 're',
  locale: 'fr_RE'
}, {
  name: 'Saint Barthélemy',
  code: 'bl',
  locale: 'fr_BL'
}, {
  name: 'Saint Helena',
  code: 'sh',
  locale: 'en_SH'
}, {
  name: 'Saint Kitts and Nevis',
  code: 'kn',
  locale: 'en_KN'
}, {
  name: 'Saint Lucia',
  code: 'lc',
  locale: 'en_LC'
}, {
  name: 'Saint Martin',
  code: 'mf',
  locale: 'fr_MF'
}, {
  name: 'Saint Pierre and Miquelon',
  code: 'pm',
  locale: 'fr_PM'
}, {
  name: 'Saint Vincent and the Grenadines',
  code: 'vc',
  locale: 'en_VC'
}, {
  name: 'Samoa',
  code: 'ws',
  locale: 'sm_WS'
}, {
  name: 'San Marino',
  code: 'sm',
  locale: 'it_SM'
}, {
  name: 'Saudi Arabia',
  code: 'sa',
  locale: 'ar_SA'
}, {
  name: 'Senegal',
  code: 'sn',
  locale: 'fr_SN'
}, {
  name: 'Serbia',
  code: 'rs',
  locale: 'sr_RS'
}, {
  name: 'Seychelles',
  code: 'sc',
  locale: 'en_SC'
}, {
  name: 'Sierra Leone',
  code: 'sl',
  locale: 'en_SL'
}, {
  name: 'Singapore',
  code: 'sg',
  locale: 'cmn'
}, {
  name: 'Sint Maarten',
  code: 'sx',
  locale: 'nl_SX'
}, {
  name: 'Slovakia',
  code: 'sk',
  locale: 'sk_SK'
}, {
  name: 'Slovenia',
  code: 'si',
  locale: 'sl_SI'
}, {
  name: 'Solomon Islands',
  code: 'sb',
  locale: 'en_SB'
}, {
  name: 'Somalia',
  code: 'so',
  locale: 'so_SO'
}, {
  name: 'South Africa',
  code: 'za',
  locale: 'en_ZA'
}, {
  name: 'South Georgia and the South Sandwich Islands',
  code: 'gs',
  locale: 'en_GS'
}, {
  name: 'South Korea',
  code: 'kr',
  locale: 'ko_KR'
}, {
  name: 'South Sudan',
  code: 'ss',
  locale: 'en_SS'
}, {
  name: 'Spain',
  code: 'es',
  locale: 'es_ES'
}, {
  name: 'Sri Lanka',
  code: 'lk',
  locale: 'si_LK'
}, {
  name: 'Sudan',
  code: 'sd',
  locale: 'ar_SD'
}, {
  name: 'Suriname',
  code: 'sr',
  locale: 'nl_SR'
}, {
  name: 'Svalbard and Jan Mayen',
  code: 'sj',
  locale: 'no_SJ'
}, {
  name: 'Sweden',
  code: 'se',
  locale: 'sv_SE'
}, {
  name: 'Switzerland',
  code: 'ch',
  locale: 'de_CH'
}, {
  name: 'Syria',
  code: 'sy',
  locale: 'ar_SY'
}, {
  name: 'São Tomé and Príncipe',
  code: 'st',
  locale: 'pt_ST'
}, {
  name: 'Taiwan',
  code: 'tw',
  locale: 'zh_TW'
}, {
  name: 'Tajikistan',
  code: 'tj',
  locale: 'tg_TJ'
}, {
  name: 'Tanzania',
  code: 'tz',
  locale: 'sw_TZ'
}, {
  name: 'Thailand',
  code: 'th',
  locale: 'th_TH'
}, {
  name: 'Timor-Leste',
  code: 'tl',
  locale: 'tet'
}, {
  name: 'Togo',
  code: 'tg',
  locale: 'fr_TG'
}, {
  name: 'Tokelau',
  code: 'tk',
  locale: 'tkl'
}, {
  name: 'Tonga',
  code: 'to',
  locale: 'to_TO'
}, {
  name: 'Trinidad and Tobago',
  code: 'tt',
  locale: 'en_TT'
}, {
  name: 'Tunisia',
  code: 'tn',
  locale: 'ar_TN'
}, {
  name: 'Turkey',
  code: 'tr',
  locale: 'tr_TR'
}, {
  name: 'Turkmenistan',
  code: 'tm',
  locale: 'tk_TM'
}, {
  name: 'Turks and Caicos Islands',
  code: 'tc',
  locale: 'en_TC'
}, {
  name: 'Tuvalu',
  code: 'tv',
  locale: 'tvl'
}, {
  name: 'U.S. Minor Outlying Islands',
  code: 'um',
  locale: 'en_UM'
}, {
  name: 'U.S. Virgin Islands',
  code: 'vi',
  locale: 'en_VI'
}, {
  name: 'Uganda',
  code: 'ug',
  locale: 'en_UG'
}, {
  name: 'Ukraine',
  code: 'ua',
  locale: 'uk_UA'
}, {
  name: 'United Arab Emirates',
  code: 'ae',
  locale: 'ar_AE'
}, {
  name: 'United Kingdom',
  code: 'gb',
  locale: 'en_GB'
}, {
  name: 'United States of America',
  code: 'us',
  locale: 'en_US'
}, {
  name: 'Uruguay',
  code: 'uy',
  locale: 'es_UY'
}, {
  name: 'Uzbekistan',
  code: 'uz',
  locale: 'uz_UZ'
}, {
  name: 'Vanuatu',
  code: 'vu',
  locale: 'bi'
}, {
  name: 'Vatican City',
  code: 'va',
  locale: 'la_VA'
}, {
  name: 'Venezuela',
  code: 've',
  locale: 'es_VE'
}, {
  name: 'Vietnam',
  code: 'vn',
  locale: 'vi_VN'
}, {
  name: 'Wallis and Futuna',
  code: 'wf',
  locale: 'wls'
}, {
  name: 'Yemen',
  code: 'ye',
  locale: 'ar_YE'
}, {
  name: 'Zambia',
  code: 'zm',
  locale: 'en_ZM'
}, {
  name: 'Zimbabwe',
  code: 'zw',
  locale: 'en_ZW'
}, {
  name: 'Åland',
  code: 'ax',
  locale: 'sv_AX'
}];
