# picom configuration

backend = "glx";
unredir-if-possible = true;
vsync = true;

wintypes: {
  dock = {
    shadow = false;
    blur-background = false;
  };
};

blur-background = true;
blur-kern = "3x3box";
blur-method = "dual_kawase";
blur-strength = 3;
