#!/bin/sh

# enable builtin vi command line editor in sh
set -o vi

# aliases
[ -f $XDG_CONFIG_HOME/aliasrc ] && . $XDG_CONFIG_HOME/aliasrc

# terminal ascii
FG=$WHITE
P=$RED

msg="tell me im pretty         "

echo -e "${FG}\
 ┌――――――――――――――――――――――――┬―――――――――┐
 ├――――――――――――――――――――――――┘ ${P}▀${FG}  ${P}▀${FG}  ${P}▀${FG} │
 │ ${P}{\__/}${NC}                           │
 │ ${P}( •.•)${NC}                           │
 │  ${P}/ >@${NC} u want this?               │
 │                                  │
 │ ${P}{\__/}${NC}                           │
 │ ${P}( •-•)${NC}                           │
 │ ${P} @< \ ${NC}${msg} │
 └――――――――――――――――――――――――――――――――――┘
${NC}"

# scrollback
HISTFILE="$SH_HISTFILE"
HISTSIZE="1000000"

# prompt
export PS1=">> "
