# See: /usr/share/doc/mpd/mpdconf.example

pid_file "$XDG_CACHE_HOME/mpd.pid"
db_file "$XDG_CACHE_HOME/mpd.db"
state_file "$XDG_CACHE_HOME/mpdstate"
log_file "$XDG_CACHE_HOME/mpd.log"
music_directory "$HOME/Music"
playlist_directory "$HOME/Music"

audio_output {
  type "pulse"
  name "pulse audio"
}
