#!/bin/sh
# collection of commonly used shell alias definitions

[ -f $XDG_CONFIG_HOME/colorrc ] && source $XDG_CONFIG_HOME/colorrc

# defaults
alias \
    ls="ls --color=auto --group-directories-first" \
    cp="cp -v" \
    mv="mv -v" \
    rm="rm -v" \
    md="mkdir -pv" \
    grep="grep --color=auto"

# session
alias \
  reboot="sudo reboot" \
  shutdown="sudo shutdown -h now"

# programs
alias \
  p="sudo pacman" \
  y="yay" \
  g="git" \
  system="sudo systemctl" \
  vim="nvim" \
  r="ranger" \
  wifi="nmtui" \
  pf="ps aux | grep" \
  pk="kill -9"

# navigation
alias \
  rc='ranger --choosedir=$XDG_CACHE_HOME/.rangerdir; LASTDIR=`cat $XDG_CACHE_HOME/.rangerdir`; cd "$LASTDIR"' \
  c="find -L $XDG_CONFIG_HOME -type f | fzf | xargs -r $EDITOR"

# media
alias \
  ytmp4="youtube-dl --add-metadata -i" \
  ytmp3="youtube-dl --add-metadata -ix"

# davinci resolve codec converter
function dav() { ffmpeg -i $1 -c:v dnxhd -profile:v 1 -pix_fmt yuv422p -c:a pcm_s16le -f mov $2 }

# firebase
alias firebase="`npm config get prefix`/bin/firebase"

