#!/bin/sh
# collection of commonly used shell aliases and definitions

# ----------------------------------------------------------------
# defaults
# ----------------------------------------------------------------

alias \
  cp="cp -v" \
  mv="mv -v" \
  rm="rm -v" \
  md="mkdir -pv" \
  grep="grep --color=auto"

case "$OS" in
  "$OS_LINUX")
    alias ls="ls --color=auto --group-directories-first"
    alias sed="sed --posix"
    alias bc="bc -w -q"
    ;;
  "$OS_OPENBSD")
    alias ls="ls -F"
    alias md="mkdir -p"
    unalias grep
    ;;
  *)
    alias ls="ls -GF"
    ;;
esac

cd() {
  builtin cd "$@" && ls
}

# ----------------------------------------------------------------
# system session
# ----------------------------------------------------------------

case "$OS" in
  "$OS_LINUX")
    alias \
      reboot="sudo reboot" \
      shutdown="sudo poweroff" \
      suspend="sudo systemctl suspend" \
      hibernate="sudo systemctl hibernate"
    ;;
  "$OS_FREEBSD")
    alias \
      reboot="sudo reboot" \
      shutdown="sudo poweroff" \
      suspend="sudo acpiconf -s 3" \
      hibernate="sudo acpiconf -s 5"
    ;;
  "$OS_OPENBSD")
    alias \
      reboot="doas reboot" \
      shutdown="doas shutdown -p now" \
      suspend="echo -e \"${RED}Suspend yourself.${NC}\"" \
      hibernate="echo -e \"${RED}What do you think I am? A bear?${NC}\""
    ;;
esac

# ----------------------------------------------------------------
# programs
# ----------------------------------------------------------------

# package manager
case "$OS" in
  "$OS_LINUX")
    alias p="sudo pacman"
    alias y="paru"
    ;;
  "$OS_FREEBSD")
    alias p="sudo pkg"
    alias y="sudo portsnap"
    ;;
  "$OS_OPENBSD")
    # refrain from using OpenBSD's package tools because it's better
    # to build from source with as few packages as possible
    p() {
      echo -e "${RED}Stop installing packages. It's bad for you.${NC}"
    }
    y() {
      p $@
    }
    ;;
esac

# core
alias \
  ch="cursor hide" \
  cs="cursor show" \
  cra="npx create-react-app --template=typescript --use-npm" \
  em="neomutt" \
  fet="pfetch" \
  lss="du -h -s" \
  n="newsboat -u $XDG_DATA_HOME/newsboat/urls -C $NEWSBOAT_CONFIG/config" \
  ss="sc-im" \
  vi="$EDITOR" \
  vim="$EDITOR" \
  webcam="devour mpv av://v4l2:/dev/video0 --profile=low-latency --untimed" \
  wget="wget --hsts-file=${XDG_DATA_HOME}/wget-hsts" \
  yarn="HOME=$YARN_RC_DIR PREFIX=$YARN_GLOBAL_DIR yarn"

case "$OS" in
  "$OS_FREEBSD")
    alias \
      hack="nethack"
    ;;
  "$OS_OPENBSD")
    alias \
      hack="nethack-${NETHACK_VER}" \
      sp="ncspot"
    ;;
  "$OS_LINUX")
    alias \
      am="alsamixer" \
      bt="aria2c" \
      cal="cal -3" \
      clearmem="sync; echo 1 | sudo tee /proc/sys/vm/drop_caches; sync" \
      hack="nethack" \
      obsv="sudo modprobe v4l2loopback devices=1 video_nr=10 card_label=\"OBS Cam\" exclusive_caps=1" \
      pin="pulse-switch-input" \
      pout="pulse-switch-output" \
      sha="sha256sum" \
      sp="ncspot" \
      system="sudo systemctl"
    ;;
esac

# latex compilation
lat() {
  if [ -z "$1" ]; then
    echo "${RED}ERROR: file not supplied${NC}"
    exit 1
  fi

  file="$(echo "$1" | cut -d '.' -f 1)"

  pdflatex "$file"
  bibtex "$file"
  pdflatex "$file"
  pdflatex "$file"
}

# this... it's not what it looks like I promise mom
mrping() {
  echo "${YELLOW}\
                   #\n\
                  //*##(*\n\
                 //,,#((%\n\
             (.,*&&&&/%\n\
                 ((#/\n\
               **  (,\n\
                   /,\n\
                   /,.\n\
                  //,,\n\
                 //**,\n\
                /(/**\n\
            .####*,**\n\
          ##(#(%%&&####\n\
        #%%#(##,,,..%%%#(\n\
       /(%%%%*,*,,,,,...*(\n\
      #(%%%&%&((((/**,,,*%\n\
    #%%(%%%%%%%%#&&&&&&\n\
    (.( # (#%%%%&&%%##\n\
    /           */*#\n\
              ,,,&,\n\
            ,*(**/&*,\n\
${NC}"
}
alias ping="mrping && ping"

# website retrieval
# note: this is only semi-effective on javascript-run sites
webget() {
  if [ -z "$1" ]; then
    echo "${RED}USAGE: webget [url]${NC}"
  else
    url="$1"
    urlEscaped="$(echo "$1" | sed -e 's/\///g')"

    # -P output dir
    # -m recursive mirror downloading
    # -p download everything required for displaying a site
    # -k use local relative links
    # -R specify a pattern of files to reject
    # -t number of retries for failed connections or errors
    # -H download files from other hosts too (images, fonts, links (oh no!))
    # --adjust-extension fix file extensions to be explicit

    wget \
      -P "$urlEscaped" \
      -m \
      -p \
      -k \
      -R "robots.txt" \
      -t 5 \
      -H \
      --adjust-extension \
      --show-progress \
      "$url"
  fi
}

# music
m() {
  if ! pgrep -x "$MUSIC_PLAYER_DAEMON" > "$NULL"; then
    $MUSIC_PLAYER_DAEMON 2> "$NULL" &
    sleep 0.3
  fi
  ncmpcpp
}
pl() {
  # devour mpv
  if [ -z "$1" ]; then
    echo "${RED}USAGE: pl [options] [playlist]${NC}"
  else
    case "$1" in
      # audio only
      *"sc"*|*"soundcloud"*) mpv "$@" ;;
      # YT video
      *) devour mpv "$@" ;;
    esac
  fi
}
alias hdmipl="pl --audio-device=alsa/plughw:0,3"

# process kill
pk() {
  proc="$(ps aux | \
    sed 1d | \
    tr -s " " | \
    cut -d " " -f1-2,11- | \
    fzf)"

  if [ -n "${proc}" ]; then
    pid="$(echo "${proc}" | cut -d " " -f 2)"
    kill -9 "$pid"
  else
    echo "${RED}No process specified.${NC}"
  fi
}

# contacts
c() {
  abook --datafile "$ADDRESS_BOOK" --config "$ABOOK_CONFIG"
}

alias zr="clear && . $ENV"

# ----------------------------------------------------------------
# version control
# ----------------------------------------------------------------

# git wrapper
#
# git clone URL --branch BRANCH
# to merge the last n remote commits in branch b:
# git rebase -i origin/b~n b
# git push origin +b
alias g="git"

# ----------------------------------------------------------------
# navigation
# ----------------------------------------------------------------

# repo browser
rp() {
  mkdir -p "$XDG_REPO_HOME"
  repo="$(ls "$XDG_REPO_HOME" | fzf)"
  cd "$XDG_REPO_HOME/$repo"
}

# file explorer directory setting
fm() {
  fmTmp="$(mktemp -t "fm.${MK_TEMP}")"
  $FILE_EXPLORER_ARGS --choose-dir="$fmTmp"
  dir="$(cat "$fmTmp" | tr ' ' '\ ')"
  rm -f "$fmTmp" > "$NULL"
  cd "$dir"
}
alias r="fm"

# bookmarks
b() {
  touch "$BOOKMARK_CONFIG"
  initialQuery="$1"
  bpath="$(cat "$BOOKMARK_CONFIG" | \
    fzf --query "$initialQuery" --select-1 | \
    cut -d',' -f2)"
  bpath="$(eval "echo $bpath")"

  if [ -z "${bpath}" ]; then
    echo "${RED}Error: invalid bookmark.${NC}"
    echo "${RED}Add new bookmarks to ${BOOKMARK_CONFIG} with the format 'identifier, path'${NC}"
    # sleep 1
    # $EDITOR "${BOOKMARK_CONFIG}"
  else
    cd "${bpath}"
  fi
}

# ----------------------------------------------------------------
# media
# ----------------------------------------------------------------

dlLink() {
  youtube-dl --add-metadata -i "$@"
  set +o noglob
}

# davinci resolve codec converter
dav() {
  ffmpeg -i "$1" -c:v dnxhd -profile:v 1 -pix_fmt yuv422p -c:a pcm_s16le -f mov "$2"
}

alias \
  ntfs="sudo ntfs-3g" \
  ytmp4="set -o noglob && dlLink -f 22" \
  ytmp3="set -o noglob && dlLink -x --audio-format mp3" \
  feh="feh --scale-down --auto-zoom"

if [ "${OS}" = "${OS_FREEBSD}" ]; then
  getusbdevs() {
    echo "$(sudo usbconfig | grep -o "^.*:" | tr -d ":")"
  }

  usboff() {
    getusbdevs | xargs -I {} sudo usbconfig -d {} power_off
    echo "usbs off"
  }

  usbon(){
    getusbdevs | xargs -I {} sudo usbconfig -d {} power_on
    echo "usbs on"
  }
fi

# archive extraction
e() {
  if [ -z "$1" ]; then
    echo "${RED}USAGE: e [archive]${NC}"
    return
  fi
  if [ -f "$1" ]; then
    # dir="$(echo "$1" | cut -d'.' -f1)"
    # mkdir -p "$dir"
    case "$1" in
      *.asar)      asar e "$1" "$dir" ;;
      *.tar.bz2)   tar xvjf "$1"    ;;
      *.tar.gz)    tar -xvf "$1"    ;;
      *.tar.xz)    tar xvJf "$1"    ;;
      *.bz2)       bunzip2 "$1"     ;;
      *.rar)       unrar x "$1"     ;;
      *.gz)        gunzip "$1"      ;;
      *.tar)       tar xvf "$1"     ;;
      *.tbz2)      tar xvjf "$1"    ;;
      *.tgz)       tar xvzf "$1"    ;;
      *.zip)       unzip "$1" -d "$dir"      ;;
      *.Z)         uncompress "$1"  ;;
      *.7z)        7z x "$1"        ;;
      *.xz)        unxz "$1"        ;;
      *.exe)       cabextract "$1"  ;;
      *)           echo "${RED}${1}: unrecognized file compression${NC}" ;;
    esac
    # cd "$dir"
  else
    echo "${RED}${1} is not a valid file${NC}"
  fi
}

# ----------------------------------------------------------------
# miscellaneous
# ----------------------------------------------------------------

alias keygen="ssh-keygen -t rsa -b 4096"
alias phone="devour scrcpy"

clearcache() {
  case "$OS" in
    "$OS_LINUX")
      # clear repository caches
      # if you want to clear the WHOLE cache, try -Scc (unrecommended)
      sudo pacman -Sc
      paru -Sc

      sudo journalctl --rotate
      sudo journalctl --vacuum-time=1d

      # clear any files in trash
      rm -r ${XDG_DATA_HOME}/Trash/* 2> "$NULL"
      rm -r ${XDG_DATA_HOME}/vifm/Trash/* 2> "$NULL"
      ;;
  esac
}

# merge pdfs
pdfmerge() {
  out="$1"
  shift
  in="$@"
  gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="$out" $in
}

# list all open windows
alias windows="wmctrl -l"

# alias refresh-keys="sudo pacman-key --refresh-keys"
# you could also try keyservers such as pgp.mit.edu or keyserver.ubuntu.com
alias get-key="gpg --keyserver keys.gnupg.net --recv-keys"
