#!/bin/sh
# collection of commonly used shell aliases and definitions

# ----------------------------------------------------------------
# defaults
# ----------------------------------------------------------------

if [ "$OS" = "$OS_LINUX" ]; then
  alias ls="ls --color=auto --group-directories-first"
  alias sed="sed --posix"
else
  alias ls="ls -GF"
fi

alias \
  cp="cp -v" \
  mv="mv -v" \
  rm="rm -v" \
  md="mkdir -pv" \
  grep="grep --color=auto"

cd() {
  builtin cd "$@" && ls
}

# ----------------------------------------------------------------
# system session
# ----------------------------------------------------------------

case "${OS}" in
  "${OS_LINUX}")
    alias \
      reboot="sudo reboot" \
      shutdown="sudo poweroff" \
      suspend="sudo systemctl suspend" \
      hibernate="sudo systemctl hibernate"
    ;;
  "${OS_FREEBSD}")
    alias \
      reboot="sudo reboot" \
      shutdown="sudo poweroff" \
      suspend="sudo acpiconf -s 3" \
      hibernate="sudo acpiconf -s 5"
    ;;
esac

if [ "${OS}" = "${OS_FREEBSD}" ]; then
  alias sl="slock"
fi

# ----------------------------------------------------------------
# programs
# ----------------------------------------------------------------

# package manager
case "${OS}" in
  "${OS_LINUX}")
    alias p="sudo pacman"
    alias y="unset GIT_CONFIG && yay --norebuild --noredownload"
    ;;
  "${OS_FREEBSD}")
    alias p="sudo pkg"
    alias y="sudo portsnap"
    ;;
esac

# core
alias \
  cal="cal -3" \
  msr="$MUSIC_PLAYER_ARGS" \
  n="newsboat -u $NEWSBOAT_CONFIG/urls -C $NEWSBOAT_CONFIG/config" \
  pdf="pdflatex" \
  s="$XDG_SCRIPT_HOME/run_script.sh" \
  sbuild="$SBUILD" \
  ss="sc-im" \
  surf="surf -g" \
  system="sudo systemctl" \
  vi="$EDITOR" \
  vim="$EDITOR" \
  wi="nmtui" \
  yarn="HOME=$YARN_RC_DIR PREFIX=$YARN_GLOBAL_DIR yarn"

# music
m() {
  if [ ! $(pgrep -x mpd) > /dev/null ]; then
    mpd &
  fi
  ncmpcpp
}

# process kill
pk() {
  proc="$(ps aux | \
    sed 1d | \
    tr -s " " | \
    cut -d " " -f1-2,11- | \
    fzf)"

  if [ -n "${proc}" ]; then
    pid="$(echo "${proc}" | cut -d " " -f 2)"
    kill -9 "$pid"
  else
    echo "${RED}No process specified.${NC}"
  fi
}

alias zr="clear && . $ENV"

# ----------------------------------------------------------------
# version control
# ----------------------------------------------------------------

# git wrapper
#
# git clone URL --branch BRANCH
# to merge the last n remote commits in branch b:
# git rebase -i origin/b~n b
# git push origin +b
alias g="git"

# ----------------------------------------------------------------
# navigation
# ----------------------------------------------------------------

# repo browser
rp() {
    mkdir -p "$XDG_REPO_HOME"
    repo="$(ls "$XDG_REPO_HOME" | fzf)"
    cd "$XDG_REPO_HOME/$repo"
}

# file explorer directory setting
fm() {
  fmDir="${XDG_CACHE_HOME}/fm_last_dir"
  $FILE_EXPLORER_ARGS --choose-dir="$fmDir"
  cd $(cat "$fmDir")
}
alias r="fm"

# bookmarks
b() {
  touch "$BOOKMARK_CONFIG"
  bpath="$(cat "$BOOKMARK_CONFIG" | fzf | cut -d',' -f2)"
  bpath="$(eval "echo $bpath")"

  if [ -z "${bpath}" ]; then
    echo "${RED}Error: invalid bookmark.${NC}"
    echo "${RED}Add new bookmarks to ${BOOKMARK_CONFIG} with the format 'identifier, path'${NC}"
    sleep 1
    $EDITOR "${BOOKMARK_CONFIG}"
  else
    cd "${bpath}"
  fi
}

# ----------------------------------------------------------------
# media
# ----------------------------------------------------------------

dlLink() {
  youtube-dl --add-metadata -i "$@"
  set +o noglob
}

# davinci resolve codec converter
dav() {
  ffmpeg -i "$1" -c:v dnxhd -profile:v 1 -pix_fmt yuv422p -c:a pcm_s16le -f mov "$2"
}

alias \
  ntfs="sudo ntfs-3g" \
  ytmp4="set -o noglob && dlLink -f 22" \
  ytmp3="set -o noglob && dlLink -x --audio-format mp3" \
  feh="feh --scale-down --auto-zoom"

if [ "${OS}" = "${OS_FREEBSD}" ]; then
  getusbdevs() {
    echo "$(sudo usbconfig | grep -o "^.*:" | tr -d ":")"
  }

  usboff() {
    getusbdevs | xargs -I {} sudo usbconfig -d {} power_off
    echo "usbs off"
  }

  usbon(){
    getusbdevs | xargs -I {} sudo usbconfig -d {} power_on
    echo "usbs on"
  }
fi

# archive extraction
e() {
  if [ -z "$1" ]; then
    echo "${RED}USAGE: e [archive]${NC}"
    return
  fi
  if [ -f "$1" ]; then
    dir="$(echo "$1" | cut -d'.' -f1)"
    mkdir -p "$dir"
    case "$1" in
      *.asar)      asar e "$1" "$dir" ;;
      *.tar.bz2)   tar xvjf "$1"    ;;
      *.tar.gz)    tar -xvf "$1"    ;;
      *.tar.xz)    tar xvJf "$1"    ;;
      *.bz2)       bunzip2 "$1"     ;;
      *.rar)       unrar x "$1"     ;;
      *.gz)        gunzip "$1"      ;;
      *.tar)       tar xvf "$1"     ;;
      *.tbz2)      tar xvjf "$1"    ;;
      *.tgz)       tar xvzf "$1"    ;;
      *.zip)       unzip "$1" -d "$dir"      ;;
      *.Z)         uncompress "$1"  ;;
      *.7z)        7z x "$1"        ;;
      *.xz)        unxz "$1"        ;;
      *.exe)       cabextract "$1"  ;;
      *)           echo "${RED}${1}: unrecognized file compression${NC}" ;;
    esac
    cd "$dir"
  else
    echo "${RED}${1} is not a valid file${NC}"
  fi
}

# ----------------------------------------------------------------
# miscellaneous
# ----------------------------------------------------------------

alias clear-cache="sync; echo 1 | sudo tee /proc/sys/vm/drop_caches"

# list all open windows
alias windows="wmctrl -l"
