#!/bin/sh
# app-specific environment variables

# general vars

BAR_HEIGHT=28
W_WIDTH=$(( $RES_WIDTH - $(( $W_GAPS + $W_BORDER_WIDTH )) * 2 )) 

if [ $CURRENT_THEME_MODE = $THEME_DARK ]; then
  export G_BG=$C_BLACK_0
  export G_BG_ALT=$C_BLACK_1
  export G_FG=$C_GRAY_1
  export G_FG_ALT=$C_GRAY_0
else
  export G_BG=$C_BLACK_0
  export G_BG_ALT=$C_BLACK_1
  export G_FG=$C_GRAY_1
  export G_FG_ALT=$C_GRAY_0
fi

export G_PRIMARY=$C_BLUE_0
export G_SECONDARY=$C_MAGENTA_0
export G_TERTIARY=$C_GREEN_0
export G_ALERT=$C_RED_0

# theme

export THEME_FG="$G_FG"
export THEME_FG_ALT="$G_FG_ALT"
export THEME_BG="$G_BG"
export THEME_PRIMARY="$G_PRIMARY"
export THEME_WARNING="$C_YELLOW_0"
export THEME_ERROR="$G_ALERT"

# bspwm

export BSPWM_TOP_Y="$(( $W_GAPS / 2 ))"
export BSPWM_TOP_PADDING=$(( $BAR_HEIGHT ))
export BSPWM_BORDER_ACTIVE=$G_FG
export BSPWM_BORDER_NORMAL=$BSPWM_BORDER_ACTIVE
export BSPWM_BORDER_FOCUSED=$BSPWM_BORDER_ACTIVE

# discord

export DISCORD_BG="$G_BG$W_ALPHA_HEX"
export DISCORD_FG="$G_FG"
export DISCORD_PRIMARY="$G_BG"

# dunst

export DUNST_WIDTH=400
export DUNST_HEIGHT=70
export DUNST_X="-$(( $W_GAPS * 2 ))"
export DUNST_Y="$DUNST_X"
export DUNST_ICON_SIZE=$(( $DUNST_HEIGHT * 0.8 ))

export DUNST_FONT="Source Code Pro Medium 12"

# higher hex means higher transparency
export DUNST_BG="$G_PRIMARY$W_ALPHA_HEX"
export DUNST_BG_CRITICAL="$G_ALERT$W_ALPHA_HEX"
export DUNST_FG="$G_FG"

# firefox

export FF_BG=$G_BG
export FF_BG_ALT=$G_BG_ALT
export FF_FG=$G_FG
export FF_FG_ALT=$G_FG_ALT
export FF_DISABLED=$G_FG_ALT
export FF_PRIMARY=$G_PRIMARY
export FF_SECONDARY=$G_SECONDARY
export FF_WARNING=$G_TERTIARY
export FF_ALERT=$G_ALERT

# picom

export PICOM_ALPHA="$(echo $(( $W_ALPHA * 100 )) | sed -e 's/\.//g')"

# polybar

export POLYBAR_X="$W_GAPS"
export POLYBAR_Y="$BSPWM_TOP_Y"
export POLYBAR_WIDTH="100%:-$(( $W_GAPS * 2 ))"
export POLYBAR_HEIGHT=$BAR_HEIGHT

export POLYBAR_BG="#00${G_BG:1}"
export POLYBAR_FG="$G_FG"
export POLYBAR_PRIMARY="$G_SECONDARY"
export POLYBAR_SECONDARY="$G_PRIMARY"
export POLYBAR_TERTIARY="$G_TERTIARY"
export POLYBAR_ALERT="$G_ALERT"

# shellmenu

export SHELLMENU_WIDTH="$W_WIDTH"
export SHELLMENU_HEIGHT=300
export SHELLMENU_X=$W_GAPS
export SHELLMENU_Y=$BSPWM_TOP_Y

export SHELLMENU_BG="$G_BG"
export SHELLMENU_FG="$G_FG"
export SHELLMENU_MATCH="$G_PRIMARY"
export SHELLMENU_SEL="$C_RED_1"
export SHELLMENU_PROMPT="$G_PRIMARY"

# spicetify

export SPICETIFY_BG="${G_BG:1}"
export SPICETIFY_BG_ALT="${G_BG_ALT:1}"
export SPICETIFY_FG="${G_FG:1}"
export SPICETIFY_PRIMARY="${G_PRIMARY:1}"
export SPICETIFY_SECONDARY="${G_SECONDARY:1}"
export SPICETIFY_TERTIARY="${G_TERTIARY:1}"
export SPICETIFY_ALERT="${G_ALERT:1}"

# st

export ST_FONT="Source Code Pro Medium:pixelsize=15:antialias=true:autohint=true"
export ST_PADDING="$(( $W_GAPS * 1.5 ))"

# zathura

export ZATHURA_BG="$($HEX2RGB $G_BG | sed -e s/b/ba/ -e s/\)/,$W_ALPHA\)/)"
export ZATHURA_BG_ALT="$($HEX2RGB $G_BG_ALT | sed -e s/b/ba/ -e s/\)/,$W_ALPHA\)/)"
export ZATHURA_FG="$G_FG"
export ZATHURA_PRIMARY="$G_PRIMARY"
