#!/bin/sh
# environment variables pertaining to colors

#
# Xresources-formatted colors
#

export C_BLACK_0="#171520"
# export C_BLACK_1="#4c516a"
export C_BLACK_1="#2e2d38"

export C_RED_0="#c83d65"
export C_RED_1="#f787a7"

export C_GREEN_0="#729a50"
export C_GREEN_1="$C_GREEN_0"

export C_YELLOW_0="#e7852e"
export C_YELLOW_1="#f1c944"

export C_BLUE_0="#519aba"
export C_BLUE_1="#4079b7"

export C_MAGENTA_0="#7d45aa"
export C_MAGENTA_1="#a074c4"

export C_CYAN_0="$C_BLUE_0"
export C_CYAN_1="#8dc9e4"

export C_GRAY_0="#b3b7bf"
export C_GRAY_1="#eceff4"

#
# terminal colors
#

export BLACK='\033[30m'
export RED='\033[31m'
export GREEN='\033[32m'
export YELLOW='\033[33m'
export BLUE='\033[34m'
export MAGENTA='\033[35m'
export CYAN='\033[36m'
export LGRAY='\033[37m'
export GRAY='\033[90m'

export NC='\033[0m'
