#!/bin/sh
# environment variables pertaining to colors

#
# Xresources-formatted colors
#

export C_BLACK_0="#c6c1aa"
export C_BLACK_1="#b0ab97"
if [ $CURRENT_THEME_MODE = $THEME_DARK ]; then
  export C_BLACK_0="#47443c"
  export C_BLACK_1="#636155"
fi

export C_RED_0="#ba795c"
export C_RED_1="#ba9a81"

export C_GREEN_0="#626e39"
export C_GREEN_1="#8c9440"

export C_YELLOW_0="#eacc79"
export C_YELLOW_1="#eadfb1"

export C_BLUE_0="#5f819d"
export C_BLUE_1="#81a2be"

export C_MAGENTA_0="#85678f"
export C_MAGENTA_1="#b294bb"

export C_CYAN_0="#44716b"
export C_CYAN_1="#5e8d87"

export C_GRAY_0="#47443c"
export C_GRAY_1="#636155"
if [ $CURRENT_THEME_MODE = $THEME_DARK ]; then
  export C_GRAY_0="#c6c1aa"
  export C_GRAY_1="#b0ab97"
fi

#
# terminal colors
#

export BLACK='\033[30m'
export RED='\033[31m'
export GREEN='\033[32m'
export YELLOW='\033[33m'
export BLUE='\033[34m'
export MAGENTA='\033[35m'
export CYAN='\033[36m'
export GRAY='\033[90m'
export WHITE='\033[37m'

export NC='\033[0m'
