#!/bin/sh

# templates
templates="$(cat "${XDG_CONFIG_HOME}/templaterc" | envsubst)"
for template in $templates; do
  det "$template"
done

# generate lesskey because less is ridiculous
command -v "lesskey" > "$NULL" && \
  lesskey "${XDG_CONFIG_HOME}/less/lesskey"
