#!/bin/sh
# to prevent errors, make sure this file is executable!

# run sxhkd if not already running
pgrep -x sxhkd > /dev/null || sxhkd &

if [ $OS = $OS_FREEBSD ]; then
  xinput set-prop "System mouse" "libinput Natural Scrolling Enabled" 1
fi

#
# general settings
#

# change desktop cursor to left pointer
xsetroot -cursor_name left_ptr &

# appearance
bspc config top_padding $BSPWM_TOP_PADDING

bspc config border_width $W_BORDER_WIDTH
bspc config window_gap $W_GAPS

bspc config active_border_color $BSPWM_BORDER_ACTIVE
bspc config normal_border_color $BSPWM_BORDER_NORMAL
bspc config focused_border_color $BSPWM_BORDER_FOCUSED

bspc config split_ratio 0.6

# no fullscreen gaps
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# bspc config merge_overlapping_monitors true

#
# custom rules
#

# media
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled

# shell popup windows
bspc rule -a '*:shellpopup' state=floating sticky="on"

#
# misc
#

# initialize workspaces and monitors
$RMONITOR

# update bar with latest wm info
$BAR_UPDATE
