# see /etc/examples/sysctl.conf for more information
machdep.lidaction=0		# 1=suspend, 2=hibernate laptop upon lid closing
machdep.pwraction=0		# ACPI power button action: 0=none, 1=shutdown, 2=suspend
hw.smt=1 # simultaneous multi threading - disabled by default since it could cause cache timing attacks - but compromises must be made
machdep.allowaperture=1 # allow access to VGA framebuffer and BIOS - see man xf86 4
