# see /etc/examples/sysctl.conf or man 2 sysctl for more information

# do not enter console on kernel panic, just reboot
ddb.panic=0

# simultaneous multi threading - disabled by default since it could cause cache timing attacks - but compromises must be made (default 0)
hw.smt=1

# enable audio input (default 0)
kern.audio.record=1

# max percent of physical memory buffer cache can use (default 20)
kern.bufcachepercent=80

# max number of files able to be open (2^15) (default 7030)
kern.maxfiles=32768
# max number of processes (2^13) (default 1310)
kern.maxproc=8192
# max number of vnodes (2^17) (default 53993)
kern.maxvnodes=131072

# never dump cores. See man 2 sysctl
# this doesn't even seem to do anything ._.
kern.nosuidcoredump=1

# explicitly setting 1. See man securelevel (default 1)
kern.securelevel=1

# max number of semaphore identifiers (2^10) (default 10)
kern.seminfo.semmni=1024
# max number of semaphores (2^10) (default 60)
kern.seminfo.semmns=1024

# max total shared memory allowed (in pages) (2^14) (default 8192)
kern.shminfo.shmall=16384
# max shared memory segment size (in bytes) (2^26) (default 33554432)
kern.shminfo.shmmax=67108864
# max shared memory ids (2^9) (default 128)
kern.shminfo.shmmni=512
# max shared memory segments per process (2^9) (default 128)
kern.shminfo.shmseg=512

# max connections a process can associate with a socket (2^9) (default 128)
kern.somaxconn=512

# allow access to VGA framebuffer and BIOS - see man 4 xf86
# this is not permitted to be changed except with certain privileges
# machdep.allowaperture=1

# 1=suspend, 2=hibernate laptop upon lid closing
machdep.lidaction=0
# ACPI power button action: 0=none, 1=shutdown, 2=suspend
machdep.pwraction=0

# enable packet forwarding (default 0)
net.inet.ip.forwarding=1
# max allowed ICMP errors to send every second (2^9) (default 100)
net.inet.icmp.errppslimit=512
# allow end to end TCP congestion notification without dropping packets (default 0)
net.inet.tcp.ecn=1
# enable RFC1323 window scaling (if not already enabled)
net.inet.tcp.rfc1323=1
# increase udp receiving window size (2^16) (default 41600)
net.inet.udp.recvspace=65536
# increase udp sending window size (2^14) (default 9216)
net.inet.udp.sendspace=16384
# enable packet forwarding for ipv6 (default 0)
net.inet6.ip6.forwarding=1

# encrypt all pages going to swap
vm.swapencrypt.enable=1
