# explicit keyboard encoding
keyboard.encoding=us
# brightness
display.brightness=5
# time in millisecs before screen turns off
display.screen_off=60000
# wake screen from kbd input, mouse input, or console input
display.kbdact=on
display.msact=on
display.outact=on
