#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a ferdi desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#88c0d0"
bspc config normal_border_color         "#434c5e"
bspc config active_border_color         "#fb4934"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
killall dunst
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
feh --bg-fill  ~/wallpaper.png
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom  --experimental-backends &
# Network Applet
nm-applet --indicator &
clipmenud &

# Cursor
xsetroot -cursor_name left_ptr &

setxkbmap -option caps:swapescape &

xset r rate 230 30
sudo light -S 30 &
