#!/bin/sh

WIDTH=2000
HEIGHT=500
BOTTOM=false
eval "$(xdotool getmouselocation --shell)"

if [ $BOTTOM = true ]; then
    : $(( pos_y = Y - HEIGHT - 20 ))
    : $(( pos_x = X - (WIDTH / 2) ))
else
    : $(( pos_y = Y + 20 ))
    : $(( pos_x = X - (WIDTH / 2) ))
fi

case "$1" in
  calendar)
      $TERM -g 64x9+$pos_x+$pos_y -n shellpopup -t calendar -f "Source Code Pro:bold:pixelsize=20" sh -c "cal -3 && sleep infinity"
      ;;

  clock)
      $TERM -g 34x9+$pos_x+$pos_y -n shellpopup -t clock sh -c "tty-clock -C 1"
      ;;

  *)
      echo "$(date +" %a %b %d %H:%M")"
      ;;
esac
