#!/bin/sh
export FILE_EXPLORER_FIFO_PID="${FILE_EXPLORER_FIFO}-${PPID}"

cleanup() {
  [ -e "$FILE_EXPLORER_FIFO_PID" ] && rm "$FILE_EXPLORER_FIFO_PID"
  pkill -P $$ 2>/dev/null
}

# create named pipe for input
[ -e "$FILE_EXPLORER_FIFO_PID" ] && rm "$FILE_EXPLORER_FIFO_PID"
mkfifo "$FILE_EXPLORER_FIFO_PID"
trap cleanup EXIT KILL TERM INT

if command -v "ueberzug"; then
  # must tail follow instead of cat to stay connected to pipe
  tail -f "$FILE_EXPLORER_FIFO_PID" | ueberzug layer --parser --silent bash &
fi

vifm --choose-dir=$fmDir
cleanup
