#!/usr/bin/env bash
readonly ID_PREVIEW="preview"

if [ -e "$FILE_EXPLORER_FIFO_PID" ] && command -v "ueberzug"; then
  if [[ "$1" == "draw" ]]; then
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                       [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                       [path]="${PWD}/$6") \
        > "$FILE_EXPLORER_FIFO_PID"
  else
    declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
        > "$FILE_EXPLORER_FIFO_PID"
  fi
fi
